### ISSUE TITLE
Add method to save session states directly without stopping the Bot

### ISSUE THREAD

**Issue by MajMcCloud** [MajMcCloud/TelegramBotFramework#2]
![image](https://user-images.githubusercontent.com/7095533/99882400-819c1e80-2c20-11eb-8e03-181255b2f940.png)

Feedback by Xilosof

**Comment by Xilosof** [comment]
I tried the method you recommended in the chat.
`bot.Sessions.SaveSessionStates(bot.StateMachine);`
**Its Work!**

Simple Demo:
`var bot = new TelegramBotBase.BotBase<forms.StartForm> (BotConfig.ApiKey);

 bot.StateMachine = new TelegramBotBase.States.JSONStateMachine (
 AppContext.BaseDirectory + "config\\states.json");
            
 bot.Start ();

 Console.WriteLine ("Bot started");

 Console.ReadLine ();
 bot.Sessions.SaveSessionStates(bot.StateMachine);`

**Comment by MajMcCloud** [comment]
we will integrate it later as a standalone method
