### ISSUE TITLE
Exception on Calling InvokeMessageLoop on DefaultMessageLoop when there is no "userevent" 

### ISSUE THREAD

**Issue by palashjhabak** [MajMcCloud/TelegramBotFramework#26]
https://github.com/MajMcCloud/TelegramBotFramework/blob/3340ef7b76c90c8971deec92c68f668aa5a79782/TelegramBotBase/Factories/MessageLoops/FormBaseMessageLoop.cs#L29

Because when there is no "userevent" `ur.RawData` is null and hence `update.Type` is null and the code throws an exception on Invoking the Message Loop manually without a user event

**Comment by MajMcCloud** [comment]
Hey!

thanks for getting back about this. I will take a look how we can solve this the "easy way".
Will get back to this inside this ticket in the next days.

Warm regards
Florian

**Comment by palashjhabak** [comment]
@MajMcCloud For now as a workaround, I have called the Form render method explicitly but I don't think that's a proper solution as everything should go through the message loop only.

**Comment by MajMcCloud** [comment]
I made a simple fix for this on the development branch. An updated nuget package 5.1.2-alpha will be available in the next minutes.

**Comment by palashjhabak** [comment]
Awesome. Thanks a lot.
