### ISSUE TITLE
Keyboard Markup always is hided when navigate to next form on phone but not on desktop

### ISSUE THREAD

**Issue by nightBaker** [MajMcCloud/TelegramBotFramework#30]
I use grid to show buttons as keyboard in AutoCleanForm.(If form is derived from FormBase everything is ok)
On telegram desktop everything is ok, but on iphone when form is shown keyboard is hided.
```
ButtonGrid grid = new ButtonGrid(btns);

grid.KeyboardType = TelegramBotBase.Enums.eKeyboardType.ReplyKeyboard;
grid.Enabled = true;
grid.HideKeyboardOnCleanup = false;
grid.ResizeKeyboard = true;
 
AddControl(grid);
```

**Comment by MajMcCloud** [comment]
Hey @nightBaker 
That is probably an "only user" setting. So when you hide the ReplyKeyboard for one bot once with the button there, it will not show new ones on its own.

Hope this helped

**Comment by MajMcCloud** [comment]
Hey @nightBaker,

did you have any news on this? Is this still relevant ?
Can you provide an example project?

Thank you!

**Comment by nightBaker** [comment]
@MajMcCloud, 
I just change `AutoCleanForm `to `FormBase` and there is no problem with hided keyboard

**Comment by MajMcCloud** [comment]
@nightBaker 

This will probably has something to do with the DeleteMode. Maybe check this, if it works setting it to OnLeavingForm.

**Comment by MajMcCloud** [comment]
I will close this issue now. Cause it would be probably a Client thing.
