### ISSUE TITLE
Exception when use Calendar/Month picker

### ISSUE THREAD

**Issue by bretbas** [MajMcCloud/TelegramBotFramework#39]
I have a simple StartForm with method OnInit - handler of Init event. In OnInit method i create calendar/month picker:
```
    private async Task OnInit(object sender, InitEventArgs ev)
    {
        MonthPicker monthPicker = new MonthPicker();
        AddControl(monthPicker);
    }
```
Also in StartForm i have overriden Render method with empty body.

When i started the bot, i got exception in Render method when i tried move to next/previous year:
![photo_2023-01-20_18-22-01](https://user-images.githubusercontent.com/26548549/213735693-6a5aba3f-ca45-4864-8565-177ec97f6ccf.jpg)

**Comment by MajMcCloud** [comment]
Please check the example project as below: https://github.com/MajMcCloud/TelegramBotFramework/blob/master/TelegramBotBase.Test/Tests/Controls/MonthPickerForm.cs

You have forgot to set a title.
