### ISSUE TITLE
Proactively Send a Form to User

### ISSUE THREAD

**Issue by palashjhabak** [MajMcCloud/TelegramBotFramework#5]
Hi,

First of all thanks for an excellent framework. 

I wanted to know if I want to send user a Form proactively without user asking for it, how do I do? All I have is User's device/chat Id stored in my database from a previous conversation and do not have any open session with user currently.

**Comment by palashjhabak** [comment]
@Xilosof No not that, user has interacted with my bot previously and then I have their Id, so thats sorted. Scenario is to send Forms without user asking for it, for example lets say I am building a flight price tracking service and want to give user a form with buttons to directly book flight when price falls below a certain price, then how do I do it? In this scenario, there is no ActiveForm for this user.

**Comment by MajMcCloud** [comment]
@palashjhabak @Xilosof 

Thanks for your request.

So there are actually multiple ways to archive something like this with the bot and the current framework "as is". I will write it down later with another comment.

Cheers

PS: maybe try our telegram group, would be receiving faster response next time 😀

**Comment by palashjhabak** [comment]
I tried to achieve it by using InvokeMessageLoop which you very recently introcuded in the framework , but the main challenge I am facing is the switching of forms context, which is messing things up.

**Comment by MajMcCloud** [comment]
Sure, give me some time to refactor my thoughts and then I'm send you some concepts. Maybe today, lately tomorrow.

**Comment by MajMcCloud** [comment]
@palashjhabak 

here we go, I hade two ways actually in mind to achive what you want to have (or thinking of):
I believe the  second one is what shows your current situation

_Something prior:
Please keep in mind that "forms" does not really exist in any telegram bot framework or the telegram api itself. What I have done is created a session mechanism which will help you with serialization and deserialitaion to "simulate" this kind of technology.
So it is highly recommended to use a SessionSerializer._


1. Your are using already Session serialization:

This brings a lot of benefits, why?

When a user interacts with your bot the framework creates a session and a context around this "situation".
In default it will only stay as long as the bot runs. To iimprove here, you have to take  a look into the readme at "session serialization" and choose a serializer or write one on your own, when you want to save this stuff inside a database for example.

Then you can, when ever you want, sent a message to the user via the "normal" telegram API with some buttons.
This do not must happen from the bot itself, it is important that it goes to the user.

In the framework you got an "UnhandledCall" Event which will get invoked on an inline message button click, when any of the current forms has not changed the EventArgs property **handled** to **true** . You can work with this. Cause inline buttons works with the "value" field not just only the text one  (like replykeyboard ones), you can choose a value like "pc_" (for price change) and then some internal id  (in total should be up to 64 bytes).

i.e. pc_12345

Then within that "UnhandledCall" event you can, catch it with the string operation "StartsWith" and move the user to the form you want to. Add the ID 12345 internally (could be a synonym as well) to that form and you are free to go.


What will happend:

- price change happens
- send the message with "price change"
- user will some times click the inline keyboard button
- your bot get the unhandled call event
- with the device id and the ID from the button value field you know what "price" has changed
- move the user over and do the "business stuff"



2. You are not using any session serialization:

Most of the stuff is quite similiar to above, With small changes.

When your not "saving" sessions (which is really easy to do), you have to start the session for the user.  (Which only works when the user has contacted your bot in the first place, as you already know)

As you stated correctly, there is no ActiveForm yet, so you have to create one.

You can add a null check here if a session already exists. If not, create one via:

var session = await < BotBase Instance>.Sessions.StartSession<A default Form, maybe an empty FormBase one>(DeviceID);

and then you got an ActiveForm in that "session" variable for this device.

Create your business form, add the properties from the "UnhandledCall" button value as well and then.

go as always: session.ActiveForm.NavigateTo(...)

The rest should become clear on trying out.

Have fun and good luck!.
Floh

**Comment by palashjhabak** [comment]
hey @MajMcCloud First of all thanks for taking out the time to reply let alone a so detailed reply. 

Although I had implemented it using a solution that was somewhat similar to your second suggested solution, but I do agree with you that saving the session is very easy and is advantageous in implementing the kind of scenario that I want. I will definitely change my code to save sessions. Thanks a lot for writing such a detailed solution. 

Now my followup question is lets say I send multiple forms to user very frequently, is it currently possible to switch the context to that particular form based on which form a user has interacted with assuming that the user can also interact with forms which are not the latest forms that were sent to them.

**Comment by MajMcCloud** [comment]
It sounds like your mixing multiple things into one question. Not sure.

So first, when sending a message to a user which is not a form (like a notification) inside any context, you will get ever that UnhandledCall event raised. It just depends on all other forms build up.

i.e. when sending 3 different messages (where every one lead to a different form at the end), the system doesn't care when the user clicks the button. It will work in any direction or order as you want it to.

Keep in mind, if you have multiple notifications (messages) for the same user/price it would make sense to:

1. Edit the existing message (you just need to keep the messageId)
2. delete the existing message (you just need to keep the messageId)

Maybe more fluent, for UI purposes.

"_is it currently possible to switch the context to that particular form based on which form a user has interacted_":

Sure! In general it will go to the latest form in the Action event, and then to the UnhandledCall event. As i said in my previous message.

Hopefully that helps, if not please clarify the question/questions.

**Comment by MajMcCloud** [comment]
@palashjhabak 

Hey! 

anything you need help with ? Or is this ticket closed ?

**Comment by MajMcCloud** [comment]
@palashjhabak 

I will close this issue now. For any other questions, open up a new one or come into our telegram group: https://t.me/tgbotbase

**Comment by palashjhabak** [comment]
> @palashjhabak
> 
> Hey!
> 
> anything you need help with ? Or can I close this ticket?

Hey sorry missed your message. Thank a lot for the detailed explaination. :) I was able to solve my issues.
