### ISSUE TITLE
Random Bug

### ISSUE THREAD

**Issue by cheditx** [MajMcCloud/TelegramBotFramework#66]
To be honest i don't know what really happened, i just got this error after receiving some updates on the bot

System.NullReferenceException: Object reference not set to an instance of an object.
   at TelegramBotBase.BotBase.Client_MessageLoop(Object sender, UpdateResult e)
   at TelegramBotBase.Base.MessageClient.OnMessageLoop(UpdateResult update)
   at TelegramBotBase.Base.MessageClient.HandleUpdateAsync(ITelegramBotClient botClient, Update update, CancellationToken cancellationToken)
   at Telegram.Bot.Polling.DefaultUpdateHandler.HandleUpdateAsync(ITelegramBotClient botClient, Update update, CancellationToken cancellationToken)
   at Telegram.Bot.Polling.DefaultUpdateReceiver.ReceiveAsync(IUpdateHandler updateHandler, CancellationToken cancellationToken)
   at Telegram.Bot.TelegramBotClientExtensions.ReceiveAsync(ITelegramBotClient botClient, IUpdateHandler updateHandler, ReceiverOptions receiverOptions, CancellationToken cancellationToken)
   at Telegram.Bot.TelegramBotClientExtensions.<>c__DisplayClass127_0.<<StartReceiving>b__0>d.MoveNext()
   
   EDIT:
   
   i ""fixed"" just by switching from the version 6.5 to 6.4

**Comment by MajMcCloud** [comment]
Hey, 6.5 has removed a lot of try/catches so you should debug a bit more into the issue.
Do you have an example project to test on ?

**Comment by cheditx** [comment]
> Hey, 6.5 has removed a lot of try/catches so you should debug a bit more into the issue. Do you have an example project to test on ?
> 
> Is this the full stack trace ? Cause there havent been changes within the last called method for a long time.

Yes its all the console print, i used a simple example code with FormBase implementation

var bot = BotBaseBuilder.Create().QuickStart<MessagesListener>("XXXXXXXXXXXXXXXXXXXXXXXX").Build();
        await bot.Start();

        Console.ReadLine();
        await bot.Stop();
        
      and then a class with MessagesListener : FormBase with Load(MessageResult)

**Comment by MajMcCloud** [comment]
> Yes its all the console print, i used a simple example code with FormBase implementation
> 
> var bot = BotBaseBuilder.Create().QuickStart("XXXXXXXXXXXXXXXXXXXXXXXX").Build(); await bot.Start();
> 
> ```
>     Console.ReadLine();
>     await bot.Stop();
>     
>   and then a class with MessagesListener : FormBase with Load(MessageResult)
> ```

I tested it as well with 
![image](https://github.com/MajMcCloud/TelegramBotFramework/assets/7095533/4adc0fd0-f535-4c14-814d-9a550141a9a5)

And it works as expected. I would say there is probably some issue within your StartForm. But I do not know exactly.

**Comment by MajMcCloud** [comment]
Did you used a StartFormFactory or just a Form ?

**Comment by cheditx** [comment]
> > Yes its all the console print, i used a simple example code with FormBase implementation
> > var bot = BotBaseBuilder.Create().QuickStart("XXXXXXXXXXXXXXXXXXXXXXXX").Build(); await bot.Start();
> > ```
> >     Console.ReadLine();
> >     await bot.Stop();
> >     
> >   and then a class with MessagesListener : FormBase with Load(MessageResult)
> > ```
> 
> I tested it as well with ![image](https://private-user-images.githubusercontent.com/7095533/344733260-4adc0fd0-f535-4c14-814d-9a550141a9a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NTg0NzIsIm5iZiI6MTcxOTg1ODE3MiwicGF0aCI6Ii83MDk1NTMzLzM0NDczMzI2MC00YWRjMGZkMC1mNTM1LTRjMTQtODE0ZC05YTU1MDE0MWE5YTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMTgyMjUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjk0NmQwYTI2OTkxYTIzYWJkYmY1MWRmN2RmZjkwOGYzN2M1Y2RlMWE2NzcyZTg1YzM0Mzk5NzZlNzBmZTljYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.itrdMFGN_7RZFr2TvoNZfVptx5GlwxEXYMoUTkFDa5o)
> 
> And it works as expected. I would say there is probably some issue within your StartForm. But I do not know exactly.
> 
> Did you sent a message or /start command to invoke the bot ?

My code worked well all the time, until i added it on a group idk what happened, i used the same FormBase as always and it just returned that error, i tried with another token and it started working again

**Comment by MajMcCloud** [comment]
Some stuff regards bot commands I groups changed. But I believe that has nothing to do, with your case.

**Comment by MajMcCloud** [comment]
> My code worked well all the time, until i added it on a group idk what happened, i used the same FormBase as always and it just returned that error, i tried with another token and it started working again

Another token means probably different group settings. If you got access to both, please check the BotFather settings for groups. There are different ones.

**Comment by MajMcCloud** [comment]
@cheditx 
So this issue can be closed ?

**Comment by cheditx** [comment]
> @cheditx So this issue can be closed ?

i don't think so, because everytime a bot join a group the bot gets an error...

**Comment by MajMcCloud** [comment]
> > @cheditx So this issue can be closed ?
> 
> i don't think so, because everytime a bot join a group the bot gets an error...

Then I need more details or an example project. I added my testbot to a group and it works fine. (I used the public available TelegramBotBase.Example project)

So please give more insights on what you do exactly.

**Comment by MajMcCloud** [comment]
Fixed via #67 and version 6.5.1
