### ISSUE TITLE
Bot Form Lifecycle

### ISSUE THREAD

**Issue by sashok2k** [MajMcCloud/TelegramBotFramework#68]
Hi

I'm building a bot which should work with other services of my applicaiton(i.e database).
Right now I'm not sure that is't correct to inject database context(or any other services) into forms. 
Reason I think so is that forms are **newer** disposed.

To justify my conserns, i would like to know lifecycle of Form component. So I will have understanding at which moment injected services will be released.

**Comment by sashok2k** [comment]
Am i right to assume that when new session started, session saved into SessionManager.SessionList, once user send message/command, session saved there, and also instanse of Form attached to session?

In code i found only one line where Session is removed from SessionList
https://github.com/MajMcCloud/TelegramBotFramework/blob/master/TelegramBotBase/SessionManager.cs#L235

Since Sessions never ended, and sesions always reference Form, it mean that form will never be disposed.

There's another place where Remove called, but that method is not called from anywhere 
https://github.com/MajMcCloud/TelegramBotFramework/blob/master/TelegramBotBase/SessionManager.cs#L81

**Comment by MajMcCloud** [comment]
Yes basically thats correct. If you do not use session storage, then its only until a restart.

You can remove it at any time, but if you do so, the hole point of the project gets almost lost.
via BotInstance.Sessions.EndSession(SessionId) you should be able to remove the session at any time.

Sessions itself will not end, but forms you navigated from to another will get disposed. So you should only keep the latest one in the cache/memory.


May I ask, how many users do have on your bot (or could become users on your bot approx.), so this could become an issue ?

**Comment by sashok2k** [comment]
We are planning to create a bot for 20-30k monthly users. They may use bot quite frequently. 
I'm evaluting different bot builing solutions.

**Comment by MajMcCloud** [comment]
Ok got it. So with the current system I would say it would work fine.

But anyway, you can extend at least the Session serialization to use Redis on your own if you wish.

I thought already about an automatic mechanism which will keep a session for x minutes of time (5 should probably fine enough) to cleanup a session then. For that I have to rebuild the SessionManager, where time is missing right now for.

When you got more time and can contribute something here, would be really helpful. At least the Redis Session serialiation.

Cheers and good success!

**Comment by Lakalaa** [comment]
How can I boost my bot monthly users
